// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWN3K2c0pZeEqV-JQ3uHyV5weIi26R0Uc',
    appId: '1:475178797192:web:9948da26d29fa7a8e3f73d',
    messagingSenderId: '475178797192',
    projectId: 'e-food-9f5f6',
    authDomain: 'e-food-9f5f6.firebaseapp.com',
    storageBucket: 'e-food-9f5f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWFRyfNgl7TtIgE-BLorIsydIn9gtx8A',
    appId: '1:475178797192:android:16cf42584ea3bb9ee3f73d',
    messagingSenderId: '475178797192',
    projectId: 'e-food-9f5f6',
    storageBucket: 'e-food-9f5f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJcAFde2M4y6AJBDrfGFikflcMIThjNw',
    appId: '1:475178797192:ios:2412ccad918d8d80e3f73d',
    messagingSenderId: '475178797192',
    projectId: 'e-food-9f5f6',
    storageBucket: 'e-food-9f5f6.appspot.com',
    iosClientId: '475178797192-vvn6gmks4ec0ag9oco9ac674lrj6k811.apps.googleusercontent.com',
    iosBundleId: 'com.example.eFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZJcAFde2M4y6AJBDrfGFikflcMIThjNw',
    appId: '1:475178797192:ios:2412ccad918d8d80e3f73d',
    messagingSenderId: '475178797192',
    projectId: 'e-food-9f5f6',
    storageBucket: 'e-food-9f5f6.appspot.com',
    iosClientId: '475178797192-vvn6gmks4ec0ag9oco9ac674lrj6k811.apps.googleusercontent.com',
    iosBundleId: 'com.example.eFood',
  );
}
